In [1]:
from sklearn import tree
import numpy as np
import pandas as pd

In [2]:
datasets = pd.read_csv("INTELLIGENT IRRIGATION SYSTEM.csv")

In [3]:
datasets.head()

crop  moisture  temp  pump
0  cotton       638    16     1
1  cotton       522    18     1
2  cotton       741    22     1
3  cotton       798    32     1
4  cotton       690    28     1

In [4]:
# Merubah kelas/kolom dari String ke Unique-Integer
datasets['crop'] = pd.factorize(datasets.crop)[0]

In [5]:
# # # Menghapus kolom ID
# datasets = datasets.drop(labels="Pregnancies", axis=1)

In [6]:
#Merubah dataframe ke array numpy
datasets = datasets.to_numpy() 

In [7]:
print(datasets)

[[   0  638   16    1]
 [   0  522   18    1]
 [   0  741   22    1]
 [   0  798   32    1]
 [   0  690   28    1]
 [   0  558   23    1]
 [   0  578   12    1]
 [   0  673   35    1]
 [   0  642   45    1]
 [   0  723   11    1]
 [   0  671   23    1]
 [   0  758   34    1]
 [   0  507   45    1]
 [   0  586   33    1]
 [   0  703   45    1]
 [   0  716   25    1]
 [   0  724   11    1]
 [   0  828   41    1]
 [   0  633   23    1]
 [   0  783   18    1]
 [   0  635   36    1]
 [   0  525   33    1]
 [   0  636   24    1]
 [   0  813   15    1]
 [   0  736   44    1]
 [   0  833   13    1]
 [   0  808   29    1]
 [   0  714   14    1]
 [   0  806   28    1]
 [   0  681   31    1]
 [   0  661   35    1]
 [   0  546   32    1]
 [   0  759   10    1]
 [   0  803   21    1]
 [   0  670   22    1]
 [   0  796   21    1]
 [   0  665   32    1]
 [   0  687   11    1]
 [   0  573   13    1]
 [   0  812   38    1]
 [   0  698   45    1]
 [   0  675   39    1]
 [   0  700   38    1]
 [   0  749

In [8]:
#Membagi datasets => 400 baris data untuk training dan 100 baris data untuk testing
dataTraining = np.concatenate((datasets[0:80, :], datasets[100:180, :]), axis=0)
dataTesting = np.concatenate((datasets[80:100, :], datasets[180:200, :]), axis=0)

In [9]:
print(dataTraining)
len(dataTraining)

[[   0  638   16    1]
 [   0  522   18    1]
 [   0  741   22    1]
 [   0  798   32    1]
 [   0  690   28    1]
 [   0  558   23    1]
 [   0  578   12    1]
 [   0  673   35    1]
 [   0  642   45    1]
 [   0  723   11    1]
 [   0  671   23    1]
 [   0  758   34    1]
 [   0  507   45    1]
 [   0  586   33    1]
 [   0  703   45    1]
 [   0  716   25    1]
 [   0  724   11    1]
 [   0  828   41    1]
 [   0  633   23    1]
 [   0  783   18    1]
 [   0  635   36    1]
 [   0  525   33    1]
 [   0  636   24    1]
 [   0  813   15    1]
 [   0  736   44    1]
 [   0  833   13    1]
 [   0  808   29    1]
 [   0  714   14    1]
 [   0  806   28    1]
 [   0  681   31    1]
 [   0  661   35    1]
 [   0  546   32    1]
 [   0  759   10    1]
 [   0  803   21    1]
 [   0  670   22    1]
 [   0  796   21    1]
 [   0  665   32    1]
 [   0  687   11    1]
 [   0  573   13    1]
 [   0  812   38    1]
 [   0  698   45    1]
 [   0  675   39    1]
 [   0  700   38    1]
 [   0  749

160

In [10]:
print(dataTesting)
len(dataTesting)

[[   0  697   25    1]
 [   0  766   39    1]
 [   0  768   17    1]
 [   0  734   16    1]
 [   0  579   45    1]
 [   0  737   34    1]
 [   0  699   22    1]
 [   0  757   43    1]
 [   0  624   15    1]
 [   0  545   29    1]
 [   0  850   16    1]
 [   0  722   26    1]
 [   0  795   15    1]
 [   0  817   18    1]
 [   0  830   44    1]
 [   0  843   41    1]
 [   0  553   35    1]
 [   0  837   30    1]
 [   0  588   18    1]
 [   0  733   26    1]
 [   0  893   39    1]
 [   0  872   10    1]
 [   0  878   29    1]
 [   0  883   40    1]
 [   0  888   44    1]
 [   0 1009   21    1]
 [   0  917   33    1]
 [   0  974   28    1]
 [   0  858   19    1]
 [   0  918   19    1]
 [   0 1021   22    1]
 [   0  986   36    1]
 [   0  968   17    1]
 [   0 1015   35    1]
 [   0  914   35    1]
 [   0  941   13    1]
 [   0  902   45    1]
 [   0  894   42    1]
 [   0 1022   45    1]
 [   0  979   10    1]]


40

In [11]:
#Memecah dataset ke input label
inputTraining = dataTraining[:,0:3]
inputTesting = dataTesting[:,0:3]
labelTraining = dataTraining[:,3]
labelTesting = dataTesting[:,3]
print(labelTraining)
len(labelTraining)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1]


160

In [12]:
#Mendefinisikan decision tree classifier
model = tree.DecisionTreeClassifier()

In [13]:
#Mentraining model
model =  model.fit(inputTraining, labelTraining)

In [14]:
#Memprediksi input data testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]
Hasil Prediksi :  [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [15]:
#Menghitung akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, " Data")
print("Prediksi Salah : ", prediksiSalah, " Data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  40  Data
Prediksi Salah :  0  Data
Akurasi :  100.0 %
